<?php
/**
 * AspectConstraint
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\taxonomy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Taxonomy API
 *
 * Use the Taxonomy API to discover the most appropriate eBay categories under which sellers can offer inventory items for sale, and the most likely categories under which buyers can browse or search for items to purchase. In addition, the Taxonomy API provides metadata about the required and recommended category aspects to include in listings, and also has two operations to retrieve parts compatibility information.
 *
 * The version of the OpenAPI document: v1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace macropage\SDKs\ebay\rest\taxonomy\Model;

use \ArrayAccess;
use \macropage\SDKs\ebay\rest\taxonomy\ObjectSerializer;

/**
 * AspectConstraint Class Doc Comment
 *
 * @category Class
 * @description This type contains information about the formatting, occurrence, and support of an aspect.
 * @package  macropage\SDKs\ebay\rest\taxonomy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class AspectConstraint implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AspectConstraint';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'aspectApplicableTo' => 'string[]',
        'aspectDataType' => 'string',
        'aspectEnabledForVariations' => 'bool',
        'aspectFormat' => 'string',
        'aspectMaxLength' => 'int',
        'aspectMode' => 'string',
        'aspectRequired' => 'bool',
        'aspectUsage' => 'string',
        'expectedRequiredByDate' => 'string',
        'itemToAspectCardinality' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'aspectApplicableTo' => null,
        'aspectDataType' => null,
        'aspectEnabledForVariations' => null,
        'aspectFormat' => null,
        'aspectMaxLength' => 'int32',
        'aspectMode' => null,
        'aspectRequired' => null,
        'aspectUsage' => null,
        'expectedRequiredByDate' => null,
        'itemToAspectCardinality' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'aspectApplicableTo' => 'aspectApplicableTo',
        'aspectDataType' => 'aspectDataType',
        'aspectEnabledForVariations' => 'aspectEnabledForVariations',
        'aspectFormat' => 'aspectFormat',
        'aspectMaxLength' => 'aspectMaxLength',
        'aspectMode' => 'aspectMode',
        'aspectRequired' => 'aspectRequired',
        'aspectUsage' => 'aspectUsage',
        'expectedRequiredByDate' => 'expectedRequiredByDate',
        'itemToAspectCardinality' => 'itemToAspectCardinality'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'aspectApplicableTo' => 'setAspectApplicableTo',
        'aspectDataType' => 'setAspectDataType',
        'aspectEnabledForVariations' => 'setAspectEnabledForVariations',
        'aspectFormat' => 'setAspectFormat',
        'aspectMaxLength' => 'setAspectMaxLength',
        'aspectMode' => 'setAspectMode',
        'aspectRequired' => 'setAspectRequired',
        'aspectUsage' => 'setAspectUsage',
        'expectedRequiredByDate' => 'setExpectedRequiredByDate',
        'itemToAspectCardinality' => 'setItemToAspectCardinality'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'aspectApplicableTo' => 'getAspectApplicableTo',
        'aspectDataType' => 'getAspectDataType',
        'aspectEnabledForVariations' => 'getAspectEnabledForVariations',
        'aspectFormat' => 'getAspectFormat',
        'aspectMaxLength' => 'getAspectMaxLength',
        'aspectMode' => 'getAspectMode',
        'aspectRequired' => 'getAspectRequired',
        'aspectUsage' => 'getAspectUsage',
        'expectedRequiredByDate' => 'getExpectedRequiredByDate',
        'itemToAspectCardinality' => 'getItemToAspectCardinality'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['aspectApplicableTo'] = $data['aspectApplicableTo'] ?? null;
        $this->container['aspectDataType'] = $data['aspectDataType'] ?? null;
        $this->container['aspectEnabledForVariations'] = $data['aspectEnabledForVariations'] ?? null;
        $this->container['aspectFormat'] = $data['aspectFormat'] ?? null;
        $this->container['aspectMaxLength'] = $data['aspectMaxLength'] ?? null;
        $this->container['aspectMode'] = $data['aspectMode'] ?? null;
        $this->container['aspectRequired'] = $data['aspectRequired'] ?? null;
        $this->container['aspectUsage'] = $data['aspectUsage'] ?? null;
        $this->container['expectedRequiredByDate'] = $data['expectedRequiredByDate'] ?? null;
        $this->container['itemToAspectCardinality'] = $data['itemToAspectCardinality'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets aspectApplicableTo
     *
     * @return string[]|null
     */
    public function getAspectApplicableTo()
    {
        return $this->container['aspectApplicableTo'];
    }

    /**
     * Sets aspectApplicableTo
     *
     * @param string[]|null $aspectApplicableTo This value indicate if the aspect identified by the aspects.localizedAspectName field is a product aspect (relevant to catalog products in the category) or an item/instance aspect, which is an aspect whose value will vary based on a particular instance of the product.
     *
     * @return self
     */
    public function setAspectApplicableTo($aspectApplicableTo)
    {
        $this->container['aspectApplicableTo'] = $aspectApplicableTo;

        return $this;
    }

    /**
     * Gets aspectDataType
     *
     * @return string|null
     */
    public function getAspectDataType()
    {
        return $this->container['aspectDataType'];
    }

    /**
     * Sets aspectDataType
     *
     * @param string|null $aspectDataType The data type of this aspect. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/commerce/taxonomy/types/txn:AspectDataTypeEnum'>eBay API documentation</a>
     *
     * @return self
     */
    public function setAspectDataType($aspectDataType)
    {
        $this->container['aspectDataType'] = $aspectDataType;

        return $this;
    }

    /**
     * Gets aspectEnabledForVariations
     *
     * @return bool|null
     */
    public function getAspectEnabledForVariations()
    {
        return $this->container['aspectEnabledForVariations'];
    }

    /**
     * Sets aspectEnabledForVariations
     *
     * @param bool|null $aspectEnabledForVariations A value of true indicates that this aspect can be used to help identify item variations.
     *
     * @return self
     */
    public function setAspectEnabledForVariations($aspectEnabledForVariations)
    {
        $this->container['aspectEnabledForVariations'] = $aspectEnabledForVariations;

        return $this;
    }

    /**
     * Gets aspectFormat
     *
     * @return string|null
     */
    public function getAspectFormat()
    {
        return $this->container['aspectFormat'];
    }

    /**
     * Sets aspectFormat
     *
     * @param string|null $aspectFormat Returned only if the value of aspectDataType identifies a data type that requires specific formatting. Currently, this field provides formatting hints as follows: DATE: YYYY, YYYYMM, YYYYMMDD NUMBER: int32, double
     *
     * @return self
     */
    public function setAspectFormat($aspectFormat)
    {
        $this->container['aspectFormat'] = $aspectFormat;

        return $this;
    }

    /**
     * Gets aspectMaxLength
     *
     * @return int|null
     */
    public function getAspectMaxLength()
    {
        return $this->container['aspectMaxLength'];
    }

    /**
     * Sets aspectMaxLength
     *
     * @param int|null $aspectMaxLength The maximum length of the item/instance aspect's value. The seller must make sure not to exceed this length when specifying the instance aspect's value for a product. This field is only returned for instance aspects.
     *
     * @return self
     */
    public function setAspectMaxLength($aspectMaxLength)
    {
        $this->container['aspectMaxLength'] = $aspectMaxLength;

        return $this;
    }

    /**
     * Gets aspectMode
     *
     * @return string|null
     */
    public function getAspectMode()
    {
        return $this->container['aspectMode'];
    }

    /**
     * Sets aspectMode
     *
     * @param string|null $aspectMode The manner in which values of this aspect must be specified by the seller (as free text or by selecting from available options). For implementation help, refer to <a href='https://developer.ebay.com/api-docs/commerce/taxonomy/types/txn:AspectModeEnum'>eBay API documentation</a>
     *
     * @return self
     */
    public function setAspectMode($aspectMode)
    {
        $this->container['aspectMode'] = $aspectMode;

        return $this;
    }

    /**
     * Gets aspectRequired
     *
     * @return bool|null
     */
    public function getAspectRequired()
    {
        return $this->container['aspectRequired'];
    }

    /**
     * Sets aspectRequired
     *
     * @param bool|null $aspectRequired A value of true indicates that this aspect is required when offering items in the specified category.
     *
     * @return self
     */
    public function setAspectRequired($aspectRequired)
    {
        $this->container['aspectRequired'] = $aspectRequired;

        return $this;
    }

    /**
     * Gets aspectUsage
     *
     * @return string|null
     */
    public function getAspectUsage()
    {
        return $this->container['aspectUsage'];
    }

    /**
     * Sets aspectUsage
     *
     * @param string|null $aspectUsage The enumeration value returned in this field will indicate if the corresponding aspect is recommended or optional. Note: This field is always returned, even for hard-mandated/required aspects (where aspectRequired: true). The value returned for required aspects will be RECOMMENDED, but they are actually required and a seller will be blocked from listing or revising an item without these aspects. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/commerce/taxonomy/types/txn:AspectUsageEnum'>eBay API documentation</a>
     *
     * @return self
     */
    public function setAspectUsage($aspectUsage)
    {
        $this->container['aspectUsage'] = $aspectUsage;

        return $this;
    }

    /**
     * Gets expectedRequiredByDate
     *
     * @return string|null
     */
    public function getExpectedRequiredByDate()
    {
        return $this->container['expectedRequiredByDate'];
    }

    /**
     * Sets expectedRequiredByDate
     *
     * @param string|null $expectedRequiredByDate The expected date after which the aspect will be required. Note: The value returned in this field specifies only an approximate date, which may not reflect the actual date after which the aspect is required.
     *
     * @return self
     */
    public function setExpectedRequiredByDate($expectedRequiredByDate)
    {
        $this->container['expectedRequiredByDate'] = $expectedRequiredByDate;

        return $this;
    }

    /**
     * Gets itemToAspectCardinality
     *
     * @return string|null
     */
    public function getItemToAspectCardinality()
    {
        return $this->container['itemToAspectCardinality'];
    }

    /**
     * Sets itemToAspectCardinality
     *
     * @param string|null $itemToAspectCardinality Indicates whether this aspect can accept single or multiple values for items in the specified category. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/commerce/taxonomy/types/txn:ItemToAspectCardinalityEnum'>eBay API documentation</a>
     *
     * @return self
     */
    public function setItemToAspectCardinality($itemToAspectCardinality)
    {
        $this->container['itemToAspectCardinality'] = $itemToAspectCardinality;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


