<?php
/**
 * Aspect
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\taxonomy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Taxonomy API
 *
 * Use the Taxonomy API to discover the most appropriate eBay categories under which sellers can offer inventory items for sale, and the most likely categories under which buyers can browse or search for items to purchase. In addition, the Taxonomy API provides metadata about the required and recommended category aspects to include in listings, and also has two operations to retrieve parts compatibility information.
 *
 * The version of the OpenAPI document: v1.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace macropage\SDKs\ebay\rest\taxonomy\Model;

use \ArrayAccess;
use \macropage\SDKs\ebay\rest\taxonomy\ObjectSerializer;

/**
 * Aspect Class Doc Comment
 *
 * @category Class
 * @description This type contains information about an item attribute (for example, color) that is appropriate or necessary for accurately describing items in a particular leaf category. Sellers are required or encouraged to provide one or more values of this aspect when offering an item in that category on eBay.
 * @package  macropage\SDKs\ebay\rest\taxonomy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Aspect implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Aspect';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'aspectConstraint' => '\macropage\SDKs\ebay\rest\taxonomy\Model\AspectConstraint',
        'aspectValues' => '\macropage\SDKs\ebay\rest\taxonomy\Model\AspectValue[]',
        'localizedAspectName' => 'string',
        'relevanceIndicator' => '\macropage\SDKs\ebay\rest\taxonomy\Model\RelevanceIndicator'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'aspectConstraint' => null,
        'aspectValues' => null,
        'localizedAspectName' => null,
        'relevanceIndicator' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'aspectConstraint' => false,
        'aspectValues' => false,
        'localizedAspectName' => false,
        'relevanceIndicator' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'aspectConstraint' => 'aspectConstraint',
        'aspectValues' => 'aspectValues',
        'localizedAspectName' => 'localizedAspectName',
        'relevanceIndicator' => 'relevanceIndicator'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'aspectConstraint' => 'setAspectConstraint',
        'aspectValues' => 'setAspectValues',
        'localizedAspectName' => 'setLocalizedAspectName',
        'relevanceIndicator' => 'setRelevanceIndicator'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'aspectConstraint' => 'getAspectConstraint',
        'aspectValues' => 'getAspectValues',
        'localizedAspectName' => 'getLocalizedAspectName',
        'relevanceIndicator' => 'getRelevanceIndicator'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('aspectConstraint', $data ?? [], null);
        $this->setIfExists('aspectValues', $data ?? [], null);
        $this->setIfExists('localizedAspectName', $data ?? [], null);
        $this->setIfExists('relevanceIndicator', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets aspectConstraint
     *
     * @return \macropage\SDKs\ebay\rest\taxonomy\Model\AspectConstraint|null
     */
    public function getAspectConstraint()
    {
        return $this->container['aspectConstraint'];
    }

    /**
     * Sets aspectConstraint
     *
     * @param \macropage\SDKs\ebay\rest\taxonomy\Model\AspectConstraint|null $aspectConstraint aspectConstraint
     *
     * @return self
     */
    public function setAspectConstraint($aspectConstraint)
    {
        if (is_null($aspectConstraint)) {
            throw new \InvalidArgumentException('non-nullable aspectConstraint cannot be null');
        }
        $this->container['aspectConstraint'] = $aspectConstraint;

        return $this;
    }

    /**
     * Gets aspectValues
     *
     * @return \macropage\SDKs\ebay\rest\taxonomy\Model\AspectValue[]|null
     */
    public function getAspectValues()
    {
        return $this->container['aspectValues'];
    }

    /**
     * Sets aspectValues
     *
     * @param \macropage\SDKs\ebay\rest\taxonomy\Model\AspectValue[]|null $aspectValues A list of valid values for this aspect (for example: <code>Red</code>, <code>Green</code>, and <code>Blue</code>), along with any constraints on those values.
     *
     * @return self
     */
    public function setAspectValues($aspectValues)
    {
        if (is_null($aspectValues)) {
            throw new \InvalidArgumentException('non-nullable aspectValues cannot be null');
        }
        $this->container['aspectValues'] = $aspectValues;

        return $this;
    }

    /**
     * Gets localizedAspectName
     *
     * @return string|null
     */
    public function getLocalizedAspectName()
    {
        return $this->container['localizedAspectName'];
    }

    /**
     * Sets localizedAspectName
     *
     * @param string|null $localizedAspectName The localized name of this aspect (for example: <code>Colour</code> on the eBay UK site). <br><br><span class=\"tablenote\"> <strong>Note:</strong> This name is always localized for the specified marketplace. </span>
     *
     * @return self
     */
    public function setLocalizedAspectName($localizedAspectName)
    {
        if (is_null($localizedAspectName)) {
            throw new \InvalidArgumentException('non-nullable localizedAspectName cannot be null');
        }
        $this->container['localizedAspectName'] = $localizedAspectName;

        return $this;
    }

    /**
     * Gets relevanceIndicator
     *
     * @return \macropage\SDKs\ebay\rest\taxonomy\Model\RelevanceIndicator|null
     */
    public function getRelevanceIndicator()
    {
        return $this->container['relevanceIndicator'];
    }

    /**
     * Sets relevanceIndicator
     *
     * @param \macropage\SDKs\ebay\rest\taxonomy\Model\RelevanceIndicator|null $relevanceIndicator relevanceIndicator
     *
     * @return self
     */
    public function setRelevanceIndicator($relevanceIndicator)
    {
        if (is_null($relevanceIndicator)) {
            throw new \InvalidArgumentException('non-nullable relevanceIndicator cannot be null');
        }
        $this->container['relevanceIndicator'] = $relevanceIndicator;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


